### PR TITLE
refactor🔀: Improved the build widget tree readability

### PR DESCRIPTION
**Pull request by yashwp**

### CODE REVIEW

**Comment by azhar1038** [comment]
Thankyou for your work in improving the readability. I will include this in the example for the stable release of version 2.2.0.

**Comment by azhar1038** [comment]
Actually the implementation has changed a bit in version 2.2.0. So if you can do this for that too, it would be better.

**Comment by yashwp** [comment]
@mdazharuddin1011999 Sure, I'll update that too.

**Comment by yashwp** [comment]
@mdazharuddin1011999 Done. You can merge this PR now.

**Comment by azhar1038** [comment]
Merged to beta instead of master.

**Pull request merged**
