### PR TITLE
Added Mobikwik and Freecharge to list of UPI apps

### PR DESCRIPTION
**Pull request by RomitRadical**

### CODE REVIEW

**Comment by azhar1038** [comment]
Thanks for showing interest in making this package better by adding Mobikwik and Freecharge and correcting my silly mistake in Readme. But I don't think package name of MiPay has changed.

**Comment by RomitRadical** [comment]
This is the link to MiPay app, you can see that its in.wallet not wallet.in unless i have the wrong app.
https://play.google.com/store/apps/details?id=com.mipay.in.wallet&hl=en_IN

**Comment by azhar1038** [comment]
The play store version isn't supported in my device and the one I have came pre-installed with MIUI 11 in my Redmi Note 4 and is being updated from GetApps. Perhaps both have different package name.

**Comment by RomitRadical** [comment]
Oh yes, I did not know about the pre-installed app. Not sure how to approach this.

**Pull request merged**
